[icons]
icons = "awesome5"

[theme]
theme = "native"

[[block]]
block = "memory"
format = " $icon $mem_used/$mem_total "

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "  $layout "

[[block]]
block = "net"
format = " $icon $device $ssid "

[[block.click]]
button = "left"
cmd = "alacritty -e nmtui"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
